CREATE TABLE IF NOT EXISTS `account_master` (
  `head` varchar(100) NOT NULL,
  `under` varchar(25) NOT NULL,
  `debit` double NOT NULL DEFAULT '0',
  `credit` double NOT NULL DEFAULT '0',
  PRIMARY KEY (`head`)
);
CREATE TABLE IF NOT EXISTS `account_transfer` (
  `billno` int NOT NULL,
  `dat` date NOT NULL,
  `category` varchar(25) NOT NULL,
  `account` varchar(100) NOT NULL,
  `amount` double NOT NULL DEFAULT '0',
  `remarks` varchar(100) NOT NULL,
  `user` varchar(15) NOT NULL,
  `last` varchar(25) NOT NULL,
  PRIMARY KEY (`billno`)
);
CREATE TABLE IF NOT EXISTS `account_voucher` (
  `billno` int NOT NULL,
  `dat` date NOT NULL,
  `whom` varchar(100) NOT NULL,
  `what` varchar(100) NOT NULL,
  `amount` double NOT NULL,
  `pby` varchar(15) NOT NULL,
  `ano` varchar(25) NOT NULL,
  `account` varchar(100) NOT NULL,
  `entry` varchar(10) NOT NULL,
  `remarks` varchar(100) NOT NULL,
  `user` varchar(15) NOT NULL,
  `last` varchar(25) NOT NULL,
  `under` varchar(25) NOT NULL,
  PRIMARY KEY (`billno`)
);
CREATE TABLE IF NOT EXISTS `alter_estimate` (
  `billno` int NOT NULL,
  `dat` date NOT NULL,
  `tim` varchar(15) NOT NULL,
  `cashier` varchar(20) NOT NULL,
  `terminal` varchar(20) NOT NULL,
  `cid` varchar(20) NOT NULL,
  `cname` varchar(100) NOT NULL,
  `pby` varchar(20) NOT NULL,
  `amount` double NOT NULL,
  `newamount` double NOT NULL,
  `reason` varchar(100) NOT NULL,
  `user` varchar(15) NOT NULL,
  `last` varchar(25) NOT NULL
);
CREATE TABLE IF NOT EXISTS `alter_estimate_delete` (
  `billno` int NOT NULL,
  `dat` date NOT NULL,
  `tim` varchar(15) NOT NULL,
  `cashier` varchar(20) NOT NULL,
  `terminal` varchar(20) NOT NULL,
  `cid` varchar(20) NOT NULL,
  `cname` varchar(100) NOT NULL,
  `pby` varchar(20) NOT NULL,
  `amount` double NOT NULL,
  `newamount` double NOT NULL,
  `reason` varchar(100) NOT NULL,
  `user` varchar(15) NOT NULL,
  `last` varchar(25) NOT NULL
);
CREATE TABLE IF NOT EXISTS `alter_sales` (
  `billno` int NOT NULL,
  `dat` date NOT NULL,
  `tim` varchar(15) NOT NULL,
  `cashier` varchar(20) NOT NULL,
  `terminal` varchar(20) NOT NULL,
  `cid` varchar(20) NOT NULL,
  `cname` varchar(100) NOT NULL,
  `pby` varchar(20) NOT NULL,
  `amount` double NOT NULL,
  `newamount` double NOT NULL,
  `reason` varchar(100) NOT NULL,
  `user` varchar(15) NOT NULL,
  `last` varchar(25) NOT NULL
);
CREATE TABLE IF NOT EXISTS `alter_sales_delete` (
  `billno` int NOT NULL,
  `dat` date NOT NULL,
  `tim` varchar(15) NOT NULL,
  `cashier` varchar(20) NOT NULL,
  `terminal` varchar(20) NOT NULL,
  `cid` varchar(20) NOT NULL,
  `cname` varchar(100) NOT NULL,
  `pby` varchar(20) NOT NULL,
  `amount` double NOT NULL,
  `newamount` double NOT NULL,
  `reason` varchar(100) NOT NULL,
  `user` varchar(15) NOT NULL,
  `last` varchar(25) NOT NULL
);
CREATE TABLE IF NOT EXISTS `atten_entry` (
  `dat` date NOT NULL,
  `sid` varchar(20) NOT NULL DEFAULT '',
  `sname` varchar(100) NOT NULL DEFAULT '',
  `desig` varchar(100) NOT NULL DEFAULT '',
  `status` varchar(100) NOT NULL DEFAULT '',
  `value` varchar(100) NOT NULL DEFAULT '',
  `remarks` varchar(100) NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS `bank` (
  `ano` varchar(20) NOT NULL,
  `aname` varchar(100) NOT NULL,
  `bank` varchar(100) NOT NULL,
  `branch` varchar(100) NOT NULL,
  `ifsc` varchar(20) NOT NULL,
  `remarks` varchar(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS `barcode` (
  `barcode` varchar(20) NOT NULL,
  `ino` int NOT NULL,
  `iname` varchar(100) NOT NULL,
  `mrp` varchar(30) NOT NULL,
  `retail_price` varchar(30) NOT NULL,
  `wholesale_price` varchar(30) NOT NULL,
  `iname1` varchar(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS `barcode_layout_settings` (
  `company_name` varchar(100) NOT NULL,
  `barcode_type` varchar(20) DEFAULT NULL,
  `barcode_width` double DEFAULT NULL,
  `barcode_height` double DEFAULT NULL,
  `font_size` double DEFAULT NULL,
  `is_auto_layout` tinyint(1) DEFAULT '1',
  `stickers_per_column` int DEFAULT '10',
  `stickers_per_row` int DEFAULT '3',
  `horizontal_gap` double DEFAULT '2',
  `vertical_gap` double DEFAULT '2',
  `page_width` double DEFAULT '210',
  `page_type` varchar(30) DEFAULT 'A4 Sheet (Full Page)',
  `margin_left` double DEFAULT '0',
  `margin_top` double DEFAULT '0',
  PRIMARY KEY (`company_name`)
);
CREATE TABLE IF NOT EXISTS `barcode_settings` (
  `company_name` varchar(100) NOT NULL,
  `field_name` varchar(50) NOT NULL,
  `include` tinyint(1) DEFAULT NULL,
  `x_pos` int DEFAULT '10',
  `y_pos` int DEFAULT '10',
  `font_size` int DEFAULT '10',
  PRIMARY KEY (`company_name`,`field_name`)
);
CREATE TABLE IF NOT EXISTS `barcode_templates` (
  `name` varchar(255) NOT NULL,
  `jrxml_data` text NOT NULL,
  PRIMARY KEY (`name`)
);
CREATE TABLE IF NOT EXISTS `cust` (
  `cid` int NOT NULL,
  `ctype` varchar(15) NOT NULL,
  `cardno` varchar(20) NOT NULL,
  `cname` varchar(100) NOT NULL,
  `add1` varchar(250) NOT NULL,
  `add2` varchar(250) NOT NULL,
  `add3` varchar(250) NOT NULL,
  `city` varchar(100) NOT NULL,
  `mobile` varchar(10) NOT NULL,
  `phone` varchar(60) NOT NULL,
  `gstno` varchar(15) NOT NULL,
  `sname` varchar(50) NOT NULL,
  `scode` varchar(5) NOT NULL,
  `climit` double NOT NULL,
  `duedays` int NOT NULL,
  `interest_rate` double NOT NULL DEFAULT 0,
  `remarks` varchar(250) NOT NULL,
  `email` varchar(100) NOT NULL,
  `company_id` varchar(50) NOT NULL DEFAULT '',
  `dl` varchar(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`cid`, `company_id`)
);
CREATE TABLE IF NOT EXISTS `cust_bal` (
  `billno` varchar(20) NOT NULL DEFAULT '',
  `dat` date NOT NULL,
  `ddate` date NOT NULL,
  `cid` varchar(20) NOT NULL,
  `cname` varchar(100) NOT NULL,
  `tot` double NOT NULL,
  `paid` double NOT NULL,
  `last` varchar(25) NOT NULL DEFAULT '',
  `company_id` varchar(50) DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS `cust_bill` (
  `sno` int NOT NULL,
  `cid` varchar(20) NOT NULL DEFAULT '',
  `cname` varchar(100) NOT NULL DEFAULT '',
  `billno` varchar(100) NOT NULL DEFAULT '',
  `dat` date NOT NULL,
  `ddate` date NOT NULL,
  `amount` double NOT NULL DEFAULT '0',
  `user` varchar(15) NOT NULL DEFAULT '0',
  `last` varchar(25) NOT NULL DEFAULT '0',
  `company_id` varchar(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`sno`, `company_id`)
);
CREATE TABLE IF NOT EXISTS `cust_pay` (
  `sno` int NOT NULL,
  `dat` date NOT NULL,
  `tim` varchar(15) NOT NULL,
  `cid` varchar(20) NOT NULL,
  `cname` varchar(100) NOT NULL,
  `billno` varchar(20) NOT NULL,
  `amount` double NOT NULL,
  `net` double NOT NULL,
  `pby` varchar(10) NOT NULL,
  `remarks` varchar(100) NOT NULL,
  `user` varchar(15) NOT NULL,
  `last` varchar(25) NOT NULL,
  `dis` double NOT NULL,
  `tot` double NOT NULL,
  `company_id` varchar(50) DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS `cust_points` (
  `cid` int NOT NULL,
  `points` double NOT NULL,
  PRIMARY KEY (`cid`)
);
CREATE TABLE IF NOT EXISTS `cust_points1` (
  `sno` int NOT NULL,
  `dat` date NOT NULL,
  `tim` varchar(15) NOT NULL,
  `cid` int NOT NULL,
  `mobile` varchar(10) NOT NULL,
  `points` double NOT NULL,
  `remarks` varchar(150) NOT NULL,
  `user` varchar(15) NOT NULL,
  `last` varchar(25) NOT NULL,
  PRIMARY KEY (`sno`)
);
CREATE TABLE IF NOT EXISTS `points_redemption` (
  `redemption_id` int NOT NULL AUTO_INCREMENT,
  `dat` date NOT NULL,
  `tim` varchar(15) NOT NULL,
  `cid` int NOT NULL,
  `cname` varchar(100) NOT NULL,
  `mobile` varchar(15) NOT NULL,
  `points_redeemed` double NOT NULL,
  `cash_amount` decimal(10,2) NOT NULL,
  `conversion_rate` decimal(5,2) NOT NULL,
  `redemption_type` varchar(20) DEFAULT 'CASH',
  `user` varchar(15) NOT NULL,
  `last` varchar(25) NOT NULL,
  `company_id` varchar(50) DEFAULT '',
  PRIMARY KEY (`redemption_id`)
);
CREATE TABLE IF NOT EXISTS `ereturn` (
  `billno` int NOT NULL,
  `dat` date NOT NULL,
  `tim` varchar(15) NOT NULL,
  `location` varchar(20) NOT NULL,
  `cashier` varchar(20) NOT NULL,
  `terminal` varchar(20) NOT NULL,
  `items` int NOT NULL,
  `quans` double NOT NULL,
  `sub` double NOT NULL,
  `disp` double NOT NULL,
  `disamt` double NOT NULL,
  `gross` double NOT NULL,
  `taxamt` double NOT NULL,
  `addamt` double NOT NULL,
  `round` double NOT NULL,
  `net` double NOT NULL,
  `pby` varchar(10) NOT NULL,
  `paid` double NOT NULL,
  `bal` double NOT NULL,
  `cash` double NOT NULL,
  `card` double NOT NULL,
  `credit` double NOT NULL,
  `others` double NOT NULL,
  `upi` double NOT NULL DEFAULT '0',
  `price_type` varchar(10) NOT NULL,
  `tax_type` varchar(25) NOT NULL,
  `tax` varchar(10) NOT NULL,
  `cid` varchar(10) NOT NULL DEFAULT '',
  `cardno` varchar(20) NOT NULL,
  `cname` varchar(100) NOT NULL,
  `mobile` varchar(10) NOT NULL,
  `user` varchar(15) NOT NULL,
  `last` varchar(25) NOT NULL,
  `company_id` varchar(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`billno`, `company_id`)
);
CREATE TABLE IF NOT EXISTS `ereturn_items` (
  `billno` int NOT NULL,
  `dat` date NOT NULL,
  `cid` varchar(10) NOT NULL DEFAULT '',
  `serial` int NOT NULL,
  `ino` int NOT NULL,
  `iname` varchar(100) NOT NULL,
  `quan` double NOT NULL,
  `mrp` double NOT NULL,
  `price` double NOT NULL,
  `amount` double NOT NULL,
  `disp` double NOT NULL,
  `disamt` double NOT NULL,
  `sub` double NOT NULL,
  `taxp` double NOT NULL,
  `taxamt` double NOT NULL,
  `total` double NOT NULL,
  `udes` varchar(10) NOT NULL,
  `barcode` varchar(20) NOT NULL,
  `hsn` varchar(10) NOT NULL,
  `tax` varchar(10) NOT NULL,
  `entry` varchar(12) NOT NULL,
  `cost_rate` double NOT NULL,
  `profit` double NOT NULL,
  `iname1` varchar(100) NOT NULL,
  `price_type` varchar(10) NOT NULL,
  `tax_type` varchar(25) NOT NULL,
  `item_type` varchar(10) NOT NULL
);
CREATE TABLE IF NOT EXISTS `estimate` (
  `billno` int NOT NULL,
  `dat` date NOT NULL,
  `tim` varchar(15) NOT NULL,
  `location` varchar(20) NOT NULL,
  `cashier` varchar(20) NOT NULL,
  `terminal` varchar(20) NOT NULL,
  `items` int NOT NULL,
  `quans` double NOT NULL,
  `sub` double NOT NULL,
  `disp` double NOT NULL,
  `disamt` double NOT NULL,
  `gross` double NOT NULL,
  `taxamt` double NOT NULL,
  `addamt` double NOT NULL,
  `round` double NOT NULL,
  `net` double NOT NULL,
  `pby` varchar(10) NOT NULL,
  `paid` double NOT NULL,
  `bal` double NOT NULL,
  `cash` double NOT NULL,
  `card` double NOT NULL,
  `credit` double NOT NULL,
  `others` double NOT NULL,
  `upi` double NOT NULL DEFAULT '0',
  `price_type` varchar(10) NOT NULL,
  `tax_type` varchar(25) NOT NULL,
  `tax` varchar(10) NOT NULL,
  `cid` varchar(10) NOT NULL DEFAULT '',
  `cardno` varchar(20) NOT NULL,
  `cname` varchar(100) NOT NULL,
  `mobile` varchar(10) NOT NULL,
  `user` varchar(15) NOT NULL,
  `last` varchar(25) NOT NULL,
  `today_points` double NOT NULL DEFAULT '0',
  `total_points` double NOT NULL DEFAULT '0',
  `cost_rate` double NOT NULL DEFAULT '0',
  `company_id` varchar(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`billno`, `company_id`)
);
CREATE TABLE IF NOT EXISTS `estimate_hold` (
  `billno` int NOT NULL,
  `location` varchar(20) NOT NULL DEFAULT '',
  `terminal` varchar(20) NOT NULL DEFAULT '',
  `cashier` varchar(20) NOT NULL DEFAULT '',
  `items` int NOT NULL,
  `quans` double NOT NULL DEFAULT '0',
  `net` double NOT NULL DEFAULT '0',
  `cname` varchar(100) NOT NULL DEFAULT '0',
  `barcode` varchar(20) NOT NULL DEFAULT '0',
  `ino` int NOT NULL DEFAULT '0',
  `iname` varchar(100) NOT NULL DEFAULT '0',
  `price` double NOT NULL DEFAULT '0',
  `quan` double NOT NULL DEFAULT '0',
  `udes` varchar(10) NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS `estimate_items` (
  `billno` int NOT NULL,
  `dat` date NOT NULL,
  `cid` varchar(10) NOT NULL DEFAULT '',
  `serial` int NOT NULL,
  `ino` int NOT NULL,
  `iname` varchar(100) NOT NULL,
  `quan` double NOT NULL,
  `mrp` double NOT NULL,
  `price` double NOT NULL,
  `amount` double NOT NULL,
  `disp` double NOT NULL,
  `disamt` double NOT NULL,
  `sub` double NOT NULL,
  `taxp` double NOT NULL,
  `taxamt` double NOT NULL,
  `total` double NOT NULL,
  `udes` varchar(10) NOT NULL,
  `barcode` varchar(20) NOT NULL,
  `hsn` varchar(10) NOT NULL,
  `tax` varchar(10) NOT NULL,
  `entry` varchar(12) NOT NULL,
  `cost_rate` double NOT NULL,
  `profit` double NOT NULL,
  `iname1` varchar(100) NOT NULL,
  `price_type` varchar(10) NOT NULL,
  `tax_type` varchar(25) NOT NULL,
  `item_type` varchar(10) NOT NULL,
  `prate` double NOT NULL DEFAULT '0',
  `rprice` double NOT NULL DEFAULT '0',
  `wprice` double NOT NULL DEFAULT '0',
  `remarks` varchar(80) DEFAULT NULL,
  `size` varchar(50) DEFAULT NULL,
  `color` varchar(50) DEFAULT NULL,
  `brand` varchar(100) DEFAULT NULL,
  `company_id` varchar(50) NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS `item` (
  `ino` int NOT NULL,
  `barcode` varchar(20) NOT NULL,
  `iname` varchar(100) NOT NULL,
  `iname1` varchar(100) NOT NULL,
  `prate` double NOT NULL,
  `taxp` int NOT NULL,
  `mrp` double NOT NULL,
  `rprice` double NOT NULL,
  `wprice` double NOT NULL,
  `cat` varchar(100) NOT NULL,
  `manu` varchar(100) NOT NULL,
  `hsn` varchar(10) NOT NULL,
  `udes` varchar(10) NOT NULL,
  `minstock` double NOT NULL,
  `maxstock` double NOT NULL,
  `rack` varchar(30) NOT NULL,
  `disp` double NOT NULL,
  `ostock` double NOT NULL,
  `subunit` varchar(10) DEFAULT NULL,
  `subconv` double DEFAULT NULL,
  `batch` varchar(50) DEFAULT NULL,
  `size` varchar(50) DEFAULT NULL,
  `color` varchar(50) DEFAULT NULL,
  `brand` varchar(100) DEFAULT NULL,
  `exp_date` date DEFAULT NULL,
  `mfg_date` date DEFAULT NULL,
  `tax_inclusion` varchar(30) NOT NULL DEFAULT 'Inclusive of Tax',
  `company_id` varchar(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`ino`, `company_id`),
  UNIQUE KEY `item_barcode_company` (`barcode`, `company_id`)
);
CREATE TABLE IF NOT EXISTS `packing` (
  `sno` int NOT NULL,
  `dat` date NOT NULL,
  `ino` int NOT NULL,
  `iname` varchar(100) NOT NULL,
  `quan` double NOT NULL DEFAULT '0',
  `weight` double NOT NULL DEFAULT '0',
  `items` int NOT NULL DEFAULT '0',
  `quans` double NOT NULL DEFAULT '0',
  `weights` double NOT NULL DEFAULT '0',
  `user` varchar(15) NOT NULL DEFAULT '0',
  `last` varchar(25) NOT NULL DEFAULT '0'
);
CREATE TABLE IF NOT EXISTS `packing_items` (
  `sno` int NOT NULL,
  `ino` int NOT NULL,
  `iname` varchar(100) NOT NULL,
  `quan` int NOT NULL DEFAULT '0',
  `weight` double NOT NULL DEFAULT '0',
  `tweight` double NOT NULL DEFAULT '0',
  `barcode` varchar(20) NOT NULL DEFAULT '0',
  `mrp` double NOT NULL DEFAULT '0',
  `rprice` double NOT NULL DEFAULT '0',
  `wprice` double NOT NULL DEFAULT '0',
  `entry` varchar(10) NOT NULL DEFAULT '0',
  `cat` varchar(100) NOT NULL DEFAULT '0',
  `prate` double NOT NULL DEFAULT '0',
  `stock_type` varchar(11) NOT NULL DEFAULT '0'
);
CREATE TABLE IF NOT EXISTS `pay_advance` (
  `sno` int NOT NULL,
  `dat` date NOT NULL,
  `cid` varchar(20) NOT NULL DEFAULT '',
  `cname` varchar(100) NOT NULL DEFAULT '',
  `amount` double NOT NULL DEFAULT '0',
  `remarks` varchar(100) NOT NULL DEFAULT '0',
  `last` varchar(25) NOT NULL DEFAULT '0',
  PRIMARY KEY (`sno`)
);
CREATE TABLE IF NOT EXISTS `pay_bill` (
  `sno` int NOT NULL,
  `dfrom` date NOT NULL,
  `dto` date NOT NULL,
  `cid` varchar(20) NOT NULL DEFAULT '',
  `cname` varchar(100) NOT NULL DEFAULT '',
  `salary` double NOT NULL DEFAULT '0',
  `days` int NOT NULL DEFAULT '0',
  `gross` double NOT NULL DEFAULT '0',
  `lpay` double NOT NULL DEFAULT '0',
  `lopay` double NOT NULL DEFAULT '0',
  `net` double NOT NULL DEFAULT '0',
  `mobile` varchar(15) NOT NULL DEFAULT '0',
  `lno` int NOT NULL DEFAULT '0',
  `balance` double NOT NULL DEFAULT '0',
  `last` varchar(25) NOT NULL DEFAULT '0',
  `dat` date NOT NULL
);
CREATE TABLE IF NOT EXISTS `pay_loan` (
  `sno` int NOT NULL,
  `dat` date NOT NULL,
  `cid` varchar(20) NOT NULL DEFAULT '',
  `cname` varchar(100) NOT NULL DEFAULT '',
  `tot` double NOT NULL DEFAULT '0',
  `paid` double NOT NULL DEFAULT '0',
  `remarks` varchar(100) NOT NULL DEFAULT '0',
  `status` varchar(10) NOT NULL DEFAULT '0',
  `last` varchar(25) NOT NULL DEFAULT '0',
  PRIMARY KEY (`sno`)
);
CREATE TABLE IF NOT EXISTS `peracc` (
  `sno` int NOT NULL AUTO_INCREMENT,
  `billno` varchar(50) NOT NULL DEFAULT '',
  `dat` date NOT NULL,
  `part` varchar(100) NOT NULL DEFAULT '',
  `debit` double NOT NULL DEFAULT '0',
  `credit` double NOT NULL DEFAULT '0',
  `account` varchar(50) NOT NULL DEFAULT '0',
  `under` varchar(50) NOT NULL DEFAULT '0',
  `type1` varchar(50) NOT NULL DEFAULT '0',
  `ano` varchar(50) NOT NULL DEFAULT '0',
  PRIMARY KEY (`sno`),
  KEY `sno` (`sno`)
);
CREATE TABLE IF NOT EXISTS `po_entry` (
  `grn` int NOT NULL,
  `dat` date NOT NULL,
  `cname` varchar(100) NOT NULL DEFAULT '',
  `items` int NOT NULL DEFAULT '0',
  `quans` double NOT NULL DEFAULT '0',
  `sub` double NOT NULL DEFAULT '0',
  `taxamt` double NOT NULL DEFAULT '0',
  `round` double NOT NULL DEFAULT '0',
  `net` double NOT NULL DEFAULT '0',
  `status` varchar(15) NOT NULL DEFAULT '0',
  `pstatus` varchar(15) NOT NULL DEFAULT '0',
  `user` varchar(15) NOT NULL DEFAULT '0',
  `last` varchar(25) NOT NULL DEFAULT '0',
  `ttype` varchar(20) NOT NULL DEFAULT '0',
  `rdate` date NOT NULL,
  `term1` varchar(200) NOT NULL DEFAULT '',
  `term2` varchar(200) NOT NULL DEFAULT '',
  `term3` varchar(200) NOT NULL DEFAULT '',
  `term4` varchar(200) NOT NULL DEFAULT '',
  `company_id` varchar(50) DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS `po_items` (
  `grn` int NOT NULL,
  `dat` date NOT NULL,
  `cname` varchar(100) NOT NULL DEFAULT '',
  `ino` int NOT NULL DEFAULT '0',
  `iname` varchar(100) NOT NULL DEFAULT '0',
  `mrp` double NOT NULL DEFAULT '0',
  `minstock` double NOT NULL DEFAULT '0',
  `stock` double NOT NULL DEFAULT '0',
  `quan` double NOT NULL DEFAULT '0',
  `free_qty` double NOT NULL DEFAULT '0',
  `price` double NOT NULL DEFAULT '0',
  `amount` double NOT NULL DEFAULT '0',
  `taxp` int NOT NULL DEFAULT '0',
  `taxamt` double NOT NULL DEFAULT '0',
  `total` double NOT NULL DEFAULT '0',
  `ttype` varchar(20) NOT NULL
);
CREATE TABLE IF NOT EXISTS `preturn` (
  `grn` int NOT NULL,
  `dat` date NOT NULL,
  `cname` varchar(100) NOT NULL,
  `billno` varchar(20) NOT NULL,
  `bdate` date NOT NULL,
  `bamount` double NOT NULL,
  `items` int NOT NULL,
  `quans` double NOT NULL,
  `sub` double NOT NULL,
  `dis` double NOT NULL,
  `gross` double NOT NULL,
  `tax` double NOT NULL,
  `fright` double NOT NULL,
  `other` double NOT NULL,
  `gt` double NOT NULL,
  `round` double NOT NULL,
  `net` double NOT NULL,
  `pby` varchar(10) NOT NULL,
  `user` varchar(15) NOT NULL,
  `last` varchar(25) NOT NULL,
  `ttype` varchar(20) NOT NULL,
  `company_id` varchar(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`grn`, `company_id`)
);
CREATE TABLE IF NOT EXISTS `preturn_items` (
  `grn` int NOT NULL,
  `dat` date NOT NULL,
  `cname` varchar(100) NOT NULL,
  `billno` varchar(20) NOT NULL,
  `bdate` date NOT NULL,
  `barcode` varchar(20) NOT NULL,
  `ino` int NOT NULL,
  `iname` varchar(100) NOT NULL,
  `mrp` double NOT NULL,
  `rprice` double NOT NULL,
  `wprice` double NOT NULL,
  `price` double NOT NULL,
  `quan` double NOT NULL,
  `amount` double NOT NULL,
  `disp` double NOT NULL,
  `disamt` double NOT NULL,
  `sub` double NOT NULL,
  `taxp` int NOT NULL,
  `taxamt` double NOT NULL,
  `total` double NOT NULL,
  `hsn` varchar(10) NOT NULL,
  `ttype` varchar(10) NOT NULL,
  `cat` varchar(100) NOT NULL,
  `manu` varchar(100) NOT NULL,
  `ttype1` varchar(20) NOT NULL
);
CREATE TABLE IF NOT EXISTS `purchase` (
  `grn` int NOT NULL,
  `dat` date NOT NULL,
  `cname` varchar(100) NOT NULL,
  `billno` varchar(20) NOT NULL,
  `bdate` date NOT NULL,
  `bamount` double NOT NULL,
  `items` int NOT NULL,
  `quans` double NOT NULL,
  `sub` double NOT NULL,
  `dis` double NOT NULL,
  `gross` double NOT NULL,
  `tax` double NOT NULL,
  `fright` double NOT NULL,
  `other` double NOT NULL,
  `gt` double NOT NULL,
  `round` double NOT NULL,
  `net` double NOT NULL,
  `pby` varchar(10) NOT NULL,
  `user` varchar(15) NOT NULL,
  `last` varchar(25) NOT NULL,
  `ttype` varchar(20) NOT NULL,
  `po_no` varchar(15) NOT NULL,
  `company_id` varchar(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`grn`, `company_id`)
);
CREATE TABLE IF NOT EXISTS `purchase_items` (
  `grn` int NOT NULL,
  `dat` date NOT NULL,
  `cname` varchar(100) NOT NULL,
  `billno` varchar(20) NOT NULL,
  `bdate` date NOT NULL,
  `barcode` varchar(20) NOT NULL,
  `ino` int NOT NULL,
  `iname` varchar(100) NOT NULL,
  `mrp` double NOT NULL,
  `rprice` double NOT NULL,
  `wprice` double NOT NULL,
  `price` double NOT NULL,
  `quan` double NOT NULL,
  `free_qty` double NOT NULL DEFAULT '0',
  `amount` double NOT NULL,
  `disp` double NOT NULL,
  `disamt` double NOT NULL,
  `sub` double NOT NULL,
  `taxp` int NOT NULL,
  `taxamt` double NOT NULL,
  `total` double NOT NULL,
  `hsn` varchar(10) NOT NULL,
  `ttype` varchar(10) NOT NULL,
  `cat` varchar(100) NOT NULL,
  `manu` varchar(100) NOT NULL,
  `ttype1` varchar(20) NOT NULL,
  `iname1` varchar(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS `sales` (
  `billno` int NOT NULL,
  `dat` date NOT NULL,
  `tim` varchar(15) NOT NULL,
  `location` varchar(20) NOT NULL,
  `cashier` varchar(20) NOT NULL,
  `terminal` varchar(20) NOT NULL,
  `items` int NOT NULL,
  `quans` double NOT NULL,
  `sub` double NOT NULL,
  `disp` double NOT NULL,
  `disamt` double NOT NULL,
  `gross` double NOT NULL,
  `taxamt` double NOT NULL,
  `addamt` double NOT NULL,
  `round` double NOT NULL,
  `net` double NOT NULL,
  `pby` varchar(10) NOT NULL,
  `paid` double NOT NULL,
  `bal` double NOT NULL,
  `cash` double NOT NULL,
  `card` double NOT NULL,
  `credit` double NOT NULL,
  `others` double NOT NULL,
  `upi` double NOT NULL DEFAULT '0',
  `price_type` varchar(10) NOT NULL,
  `tax_type` varchar(25) NOT NULL,
  `tax` varchar(10) NOT NULL,
  `cid` varchar(10) NOT NULL DEFAULT '',
  `cardno` varchar(20) NOT NULL,
  `cname` varchar(100) NOT NULL,
  `mobile` varchar(10) NOT NULL,
  `user` varchar(15) NOT NULL,
  `last` varchar(25) NOT NULL,
  `today_points` double NOT NULL DEFAULT '0',
  `total_points` double NOT NULL DEFAULT '0',
  `cost_rate` double NOT NULL DEFAULT '0',
  `company_id` varchar(50) NOT NULL DEFAULT '',
  `loyalty_points` varchar(10) DEFAULT '0.00',
  PRIMARY KEY (`billno`, `company_id`)
);
CREATE TABLE IF NOT EXISTS `sales_hold` (
  `billno` int NOT NULL,
  `location` varchar(20) NOT NULL DEFAULT '',
  `terminal` varchar(20) NOT NULL DEFAULT '',
  `cashier` varchar(20) NOT NULL DEFAULT '',
  `items` int NOT NULL,
  `quans` double NOT NULL DEFAULT '0',
  `net` double NOT NULL DEFAULT '0',
  `cname` varchar(100) NOT NULL DEFAULT '0',
  `barcode` varchar(20) NOT NULL DEFAULT '0',
  `ino` int NOT NULL DEFAULT '0',
  `iname` varchar(100) NOT NULL DEFAULT '0',
  `price` double NOT NULL DEFAULT '0',
  `quan` double NOT NULL DEFAULT '0',
  `remarks` varchar(80) DEFAULT NULL,
  `unit` varchar(100) DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS `sales_items` (
  `billno` int NOT NULL,
  `dat` date NOT NULL,
  `cid` varchar(10) NOT NULL DEFAULT '',
  `serial` int NOT NULL,
  `ino` int NOT NULL,
  `iname` varchar(100) NOT NULL,
  `quan` double NOT NULL,
  `mrp` double NOT NULL,
  `price` double NOT NULL,
  `amount` double NOT NULL,
  `disp` double NOT NULL,
  `disamt` double NOT NULL,
  `sub` double NOT NULL,
  `taxp` double NOT NULL,
  `taxamt` double NOT NULL,
  `total` double NOT NULL,
  `udes` varchar(10) NOT NULL,
  `barcode` varchar(20) NOT NULL,
  `hsn` varchar(10) NOT NULL,
  `tax` varchar(10) NOT NULL,
  `entry` varchar(12) NOT NULL,
  `cost_rate` double NOT NULL,
  `profit` double NOT NULL,
  `iname1` varchar(100) NOT NULL,
  `price_type` varchar(10) NOT NULL,
  `tax_type` varchar(25) NOT NULL,
  `item_type` varchar(10) NOT NULL,
  `prate` double NOT NULL DEFAULT '0',
  `rprice` double NOT NULL DEFAULT '0',
  `wprice` double NOT NULL DEFAULT '0',
  `remarks` varchar(80) DEFAULT NULL,
  `size` varchar(50) DEFAULT NULL,
  `color` varchar(50) DEFAULT NULL,
  `brand` varchar(100) DEFAULT NULL,
  `company_id` varchar(50) NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS `company` (
  `cname` varchar(250) NOT NULL,
  `add1` varchar(250) NOT NULL,
  `add2` varchar(250) NOT NULL,
  `add3` varchar(250) NOT NULL,
  `add4` varchar(250) NOT NULL,
  `state` varchar(50) NOT NULL,
  `scode` varchar(10) NOT NULL,
  `ttype` varchar(25) NOT NULL,
  `letter` varchar(10) NOT NULL,
  `bformat` varchar(40) NOT NULL,
  `bhead` varchar(100) NOT NULL,
  `sms1` varchar(250) NOT NULL,
  `sms2` varchar(250) NOT NULL,
  `sms3` varchar(250) NOT NULL,
  `sms4` varchar(250) NOT NULL,
  `lmargin` double NOT NULL,
  `maxdis` double NOT NULL,
  `lines1` int NOT NULL,
  `port` varchar(10) NOT NULL,
  `rprice` varchar(30) NOT NULL,
  `wprice` varchar(30) NOT NULL,
  `stock_bill` varchar(5) NOT NULL,
  `print_name` varchar(25) NOT NULL,
  `less_prate` varchar(5) NOT NULL,
  `last` varchar(25) NOT NULL,
  `rdis` double NOT NULL,
  `wdis` double NOT NULL,
  `entry_mode` varchar(10) NOT NULL,
  `bformat1` varchar(40) NOT NULL,
  `pur_rate_edit` varchar(5) NOT NULL,
  `cust_details` varchar(5) NOT NULL,
  `dsales` varchar(10) NOT NULL,
  `ehead` varchar(100) NOT NULL,
  `eformat1` varchar(40) NOT NULL,
  `eformat2` varchar(40) NOT NULL,
  `hmany` int NOT NULL DEFAULT '0',
  `round` varchar(5) NOT NULL DEFAULT '0',
  `cur_name` varchar(20) NOT NULL DEFAULT '0',
  `cur_symbol` varchar(10) NOT NULL DEFAULT '0',
  `upi_id` varchar(150) DEFAULT NULL,
  `batch` varchar(10) DEFAULT 'Batch',
  `exp` tinyint(1) DEFAULT NULL,
  `mfg` tinyint(1) DEFAULT NULL,
  `weighing_button` varchar(5) NOT NULL DEFAULT 'Yes',
  `logo_path` varchar(500) DEFAULT NULL,
  `companyID` varchar(50) DEFAULT NULL,
  `shop_type` varchar(30) DEFAULT 'General',
  `bank_name` varchar(150) DEFAULT '',
  `bank_acc_no` varchar(50) DEFAULT '',
  `bank_ifsc` varchar(20) DEFAULT '',
  `bank_branch` varchar(150) DEFAULT '',
  `bank_holder` varchar(150) DEFAULT '',
  `sales_terms` text DEFAULT NULL,
  `estimate_terms` text DEFAULT NULL,
  `estimate_stock_minus` varchar(5) NOT NULL DEFAULT 'No',
  `privacy_mode` varchar(5) NOT NULL DEFAULT 'No',
  `dl` varchar(100) NOT NULL DEFAULT '',
  CONSTRAINT `company_chk_1` CHECK ((`batch` in ('Batch','Size')))
);
CREATE TABLE IF NOT EXISTS `setting_email` (
  `user` varchar(100) NOT NULL,
  `pass` varchar(100) NOT NULL,
  `backup_option` varchar(5) NOT NULL,
  `statement_option` varchar(5) NOT NULL,
  `email1` varchar(100) NOT NULL,
  PRIMARY KEY (`user`)
);
CREATE TABLE IF NOT EXISTS `setting_points` (
  `points_option` varchar(5) NOT NULL,
  `hmuch` int NOT NULL DEFAULT '0',
  `pfor` int NOT NULL DEFAULT '0',
  `min_redemption` int NOT NULL DEFAULT '100',
  `conversion_rate` decimal(5,2) NOT NULL DEFAULT '1.00',
  `redemption_enabled` varchar(5) NOT NULL DEFAULT 'Yes',
  PRIMARY KEY (`points_option`)
);
CREATE TABLE IF NOT EXISTS `setting_sms` (
  `sender` varchar(6) NOT NULL,
  `user` varchar(100) NOT NULL,
  `pass` varchar(100) NOT NULL,
  `sms_alert` varchar(5) NOT NULL,
  `alter_sms` varchar(5) NOT NULL,
  `statement_sms` varchar(5) NOT NULL,
  `mobile1` varchar(10) NOT NULL,
  `mobile2` varchar(10) NOT NULL,
  `smsfoot1` varchar(100) NOT NULL,
  `smsfoot2` varchar(100) NOT NULL,
  PRIMARY KEY (`user`)
);
CREATE TABLE IF NOT EXISTS `setting_user` (
  `status` varchar(100) NOT NULL,
  `dat` varchar(50) NOT NULL DEFAULT '',
  `vname` varchar(150) NOT NULL,
  `hname` varchar(500) NOT NULL,
  `mname` varchar(500) NOT NULL,
  `cid` varchar(100) NOT NULL DEFAULT '',
  `cname` varchar(500) NOT NULL,
  `uname` varchar(300) NOT NULL,
  `eno` varchar(100) NOT NULL DEFAULT '0',
  `vdate` date DEFAULT NULL,
  `log` varchar(5000) DEFAULT NULL,
  `pass` varchar(100) DEFAULT NULL,
  `user_valid_date` varchar(500) DEFAULT NULL,
  `create_date` varchar(500) DEFAULT NULL,
  PRIMARY KEY (`uname`),
  UNIQUE KEY `status` (`status`),
  UNIQUE KEY `cname` (`cname`)
);
CREATE TABLE IF NOT EXISTS `app_sync_status` (
  `id` int NOT NULL AUTO_INCREMENT,
  `license_uname` varchar(255) DEFAULT NULL,
  `license_cid` varchar(100) DEFAULT NULL,
  `last_cloud_sync` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
);
CREATE TABLE IF NOT EXISTS `sreturn` (
  `billno` int NOT NULL,
  `dat` date NOT NULL,
  `tim` varchar(15) NOT NULL,
  `location` varchar(20) NOT NULL,
  `cashier` varchar(20) NOT NULL,
  `terminal` varchar(20) NOT NULL,
  `items` int NOT NULL,
  `quans` double NOT NULL,
  `sub` double NOT NULL,
  `disp` double NOT NULL,
  `disamt` double NOT NULL,
  `gross` double NOT NULL,
  `taxamt` double NOT NULL,
  `addamt` double NOT NULL,
  `round` double NOT NULL,
  `net` double NOT NULL,
  `pby` varchar(10) NOT NULL,
  `paid` double NOT NULL,
  `bal` double NOT NULL,
  `cash` double NOT NULL,
  `card` double NOT NULL,
  `credit` double NOT NULL,
  `others` double NOT NULL,
  `upi` double NOT NULL DEFAULT '0',
  `price_type` varchar(10) NOT NULL,
  `tax_type` varchar(25) NOT NULL,
  `tax` varchar(10) NOT NULL,
  `cid` varchar(10) NOT NULL DEFAULT '',
  `cardno` varchar(20) NOT NULL,
  `cname` varchar(100) NOT NULL,
  `mobile` varchar(10) NOT NULL,
  `user` varchar(15) NOT NULL,
  `last` varchar(25) NOT NULL,
  `company_id` varchar(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`billno`, `company_id`)
);
CREATE TABLE IF NOT EXISTS `sreturn_items` (
  `billno` int NOT NULL,
  `dat` date NOT NULL,
  `cid` varchar(10) NOT NULL DEFAULT '',
  `serial` int NOT NULL,
  `ino` int NOT NULL,
  `iname` varchar(100) NOT NULL,
  `quan` double NOT NULL,
  `mrp` double NOT NULL,
  `price` double NOT NULL,
  `amount` double NOT NULL,
  `disp` double NOT NULL,
  `disamt` double NOT NULL,
  `sub` double NOT NULL,
  `taxp` double NOT NULL,
  `taxamt` double NOT NULL,
  `total` double NOT NULL,
  `udes` varchar(10) NOT NULL,
  `barcode` varchar(20) NOT NULL,
  `hsn` varchar(10) NOT NULL,
  `tax` varchar(10) NOT NULL,
  `entry` varchar(12) NOT NULL,
  `cost_rate` double NOT NULL,
  `profit` double NOT NULL,
  `iname1` varchar(100) NOT NULL,
  `price_type` varchar(10) NOT NULL,
  `tax_type` varchar(25) NOT NULL,
  `item_type` varchar(10) NOT NULL
);
CREATE TABLE IF NOT EXISTS `staff_entry` (
  `sno` int NOT NULL,
  `dat` date NOT NULL,
  `tim` varchar(15) NOT NULL,
  `account` varchar(100) NOT NULL,
  `desig` varchar(100) NOT NULL,
  `sid` varchar(20) NOT NULL,
  `jdate` date NOT NULL,
  `sname` varchar(100) NOT NULL,
  `fname` varchar(100) NOT NULL,
  `gender` varchar(10) NOT NULL,
  `bg` varchar(20) NOT NULL,
  `dob` date NOT NULL,
  `religion` varchar(50) NOT NULL DEFAULT '',
  `nation` varchar(50) NOT NULL DEFAULT '',
  `add1` varchar(250) NOT NULL DEFAULT '',
  `add2` varchar(250) NOT NULL DEFAULT '',
  `add3` varchar(250) NOT NULL DEFAULT '',
  `area` varchar(100) NOT NULL DEFAULT '',
  `pincode` varchar(10) NOT NULL DEFAULT '',
  `mobile` varchar(10) NOT NULL DEFAULT '',
  `phone` varchar(60) NOT NULL DEFAULT '',
  `email` varchar(100) NOT NULL DEFAULT '',
  `mstatus` varchar(10) NOT NULL DEFAULT '',
  `family` varchar(150) NOT NULL DEFAULT '',
  `edu` varchar(150) NOT NULL DEFAULT '',
  `exp` varchar(150) NOT NULL DEFAULT '',
  `job` varchar(150) NOT NULL DEFAULT '',
  `langu` varchar(100) NOT NULL DEFAULT '',
  `adhaar` varchar(20) NOT NULL DEFAULT '',
  `acno` varchar(20) NOT NULL DEFAULT '',
  `remarks` varchar(150) NOT NULL DEFAULT '',
  `status` varchar(10) NOT NULL DEFAULT '',
  `edate` date NOT NULL,
  `salary` double NOT NULL DEFAULT '0',
  PRIMARY KEY (`sid`),
  UNIQUE KEY `sno` (`sno`),
  UNIQUE KEY `staff_entry_sid` (`sid`)
);
CREATE TABLE IF NOT EXISTS `staff_photo` (
  `sid` varchar(20) NOT NULL,
  `photo` blob NOT NULL,
  UNIQUE KEY `staff_photo_sid` (`sid`)
);
CREATE TABLE IF NOT EXISTS `stock` (
  `barcode` varchar(20) NOT NULL,
  `ino` int NOT NULL,
  `iname` varchar(100) NOT NULL,
  `mrp` double NOT NULL,
  `rprice` double NOT NULL,
  `wprice` double NOT NULL,
  `prate` double NOT NULL,
  `quan` double NOT NULL,
  `cat` varchar(100) NOT NULL,
  `entry` varchar(12) NOT NULL,
  `company_id` varchar(50) NOT NULL DEFAULT '',
  UNIQUE KEY `stock_ino_company` (`ino`,`company_id`),
  UNIQUE KEY `stock_barcode_company` (`barcode`,`company_id`)
);
CREATE TABLE IF NOT EXISTS `stock_alter` (
  `sno` int NOT NULL,
  `dat` date NOT NULL,
  `etype` varchar(5) NOT NULL,
  `ino` int NOT NULL,
  `iname` varchar(100) NOT NULL,
  `quan` double NOT NULL DEFAULT '0',
  `entry` varchar(10) NOT NULL DEFAULT '0',
  `stock_type` varchar(10) NOT NULL DEFAULT '0',
  `items` int NOT NULL DEFAULT '0',
  `quans` double NOT NULL DEFAULT '0',
  `user` varchar(15) NOT NULL DEFAULT '0',
  `last` varchar(25) NOT NULL DEFAULT '0'
);
CREATE TABLE IF NOT EXISTS `stock_entry` (
  `grn` int NOT NULL,
  `dat` date NOT NULL,
  `cname` varchar(100) NOT NULL,
  `billno` varchar(20) NOT NULL,
  `bdate` date NOT NULL,
  `bamount` double NOT NULL,
  `items` int NOT NULL,
  `quans` double NOT NULL,
  `sub` double NOT NULL,
  `dis` double NOT NULL,
  `gross` double NOT NULL,
  `tax` double NOT NULL,
  `fright` double NOT NULL,
  `other` double NOT NULL,
  `gt` double NOT NULL,
  `round` double NOT NULL,
  `net` double NOT NULL,
  `pby` varchar(10) NOT NULL,
  `user` varchar(15) NOT NULL,
  `last` varchar(25) NOT NULL,
  `ttype` varchar(25) NOT NULL,
  `dis1` double NOT NULL DEFAULT '0',
  `company_id` varchar(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`grn`, `company_id`)
);
CREATE TABLE IF NOT EXISTS `stock_entry_items` (
  `grn` int NOT NULL,
  `dat` date NOT NULL,
  `cname` varchar(100) NOT NULL,
  `billno` varchar(20) NOT NULL,
  `bdate` date NOT NULL,
  `barcode` varchar(20) NOT NULL,
  `ino` int NOT NULL,
  `iname` varchar(100) NOT NULL,
  `mrp` double NOT NULL,
  `rprice` double NOT NULL,
  `wprice` double NOT NULL,
  `price` double NOT NULL,
  `quan` double NOT NULL,
  `amount` double NOT NULL,
  `disp` double NOT NULL,
  `disamt` double NOT NULL,
  `sub` double NOT NULL,
  `taxp` int NOT NULL,
  `taxamt` double NOT NULL,
  `total` double NOT NULL,
  `hsn` varchar(10) NOT NULL,
  `ttype` varchar(10) NOT NULL,
  `cat` varchar(100) NOT NULL,
  `manu` varchar(100) NOT NULL,
  `ttype1` varchar(25) NOT NULL,
  `iname1` varchar(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS `user_features` (
  `sno` int NOT NULL DEFAULT '0',
  `fname` varchar(25) NOT NULL,
  PRIMARY KEY (`fname`)
);
CREATE TABLE IF NOT EXISTS `users` (
  `utype` varchar(150) NOT NULL,
  `user` varchar(150) NOT NULL,
  `pass` varchar(100) NOT NULL,
  `last` varchar(100) NOT NULL,
  KEY `idx_user` (`user`)
);
CREATE TABLE IF NOT EXISTS `users_permissions` (
  `user` varchar(15) NOT NULL,
  `fname` varchar(50) NOT NULL,
  `option1` varchar(5) NOT NULL,
  UNIQUE KEY `uk_user_fname` (`user`, `fname`)
);
CREATE TABLE IF NOT EXISTS `ven_bal` (
  `billno` varchar(20) NOT NULL DEFAULT '',
  `dat` date NOT NULL,
  `ddate` date NOT NULL,
  `cname` varchar(100) NOT NULL,
  `tot` double NOT NULL,
  `paid` double NOT NULL,
  `last` varchar(25) NOT NULL DEFAULT '',
  `company_id` varchar(50) DEFAULT NULL
);
CREATE TABLE IF NOT EXISTS `ven_bill` (
  `sno` int NOT NULL,
  `cname` varchar(100) NOT NULL DEFAULT '',
  `billno` varchar(100) NOT NULL DEFAULT '',
  `dat` date NOT NULL,
  `ddate` date NOT NULL,
  `amount` double NOT NULL DEFAULT '0',
  `remarks` varchar(150) NOT NULL DEFAULT '0',
  `user` varchar(15) NOT NULL DEFAULT '0',
  `last` varchar(25) NOT NULL DEFAULT '0',
  `company_id` varchar(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`sno`, `company_id`)
);
CREATE TABLE IF NOT EXISTS `ven_pay` (
  `sno` int NOT NULL,
  `dat` date NOT NULL,
  `tim` varchar(15) NOT NULL,
  `cname` varchar(100) NOT NULL,
  `billno` varchar(20) NOT NULL,
  `amount` double NOT NULL,
  `net` double NOT NULL,
  `pby` varchar(10) NOT NULL,
  `remarks` varchar(100) NOT NULL,
  `user` varchar(15) NOT NULL,
  `last` varchar(25) NOT NULL,
  `company_id` varchar(50) NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS `vendor` (
  `cname` varchar(100) NOT NULL DEFAULT '',
  `add1` varchar(250) NOT NULL DEFAULT '',
  `add2` varchar(250) NOT NULL DEFAULT '',
  `add3` varchar(250) NOT NULL DEFAULT '',
  `city` varchar(100) NOT NULL DEFAULT '',
  `mobile` varchar(10) NOT NULL DEFAULT '',
  `phone` varchar(60) NOT NULL DEFAULT '',
  `gstno` varchar(15) NOT NULL DEFAULT '',
  `sname` varchar(50) NOT NULL,
  `scode` varchar(5) NOT NULL,
  `duedays` int NOT NULL DEFAULT '0',
  `remarks` varchar(250) NOT NULL DEFAULT '0',
  `email` varchar(100) NOT NULL DEFAULT '0',
  `company_id` varchar(50) NOT NULL DEFAULT '',
  PRIMARY KEY (`cname`, `company_id`)
);
CREATE TABLE IF NOT EXISTS `vendor_link` (
  `cname` varchar(100) NOT NULL,
  `ino` int NOT NULL,
  `iname` varchar(100) NOT NULL,
  `cat` varchar(100) NOT NULL,
  `manu` varchar(100) NOT NULL,
  `taxp` int NOT NULL DEFAULT '0',
  `minstock` double NOT NULL DEFAULT '0',
  `last` varchar(25) NOT NULL
);
CREATE TABLE IF NOT EXISTS `authorized_terminals` (
  `hwid` varchar(255) NOT NULL,
  `label` varchar(255) DEFAULT NULL,
  `first_seen` datetime DEFAULT NULL,
  PRIMARY KEY (`hwid`)
);
CREATE TABLE IF NOT EXISTS `access_requests` (
  `hwid` varchar(255) NOT NULL,
  `label` varchar(255) DEFAULT NULL,
  `request_time` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`hwid`)
);
INSERT IGNORE INTO `user_features` (`sno`, `fname`) VALUES
(1, 'Sales'),
(2, 'Purchase'),
(3, 'Estimate'),
(4, 'Item'),
(5, 'Stock'),
(6, 'PO'),
(7, 'Packing'),
(8, 'Accounts'),
(9, 'Supplier'),
(10, 'Customer'),
(11, 'HR'),
(12, 'Tax Reports'),
(13, 'SMS'),
(14, 'Email'),
(15, 'Manual Barcode'),
(16, 'Loyalty'),
(17, 'Backup'),
(18, 'Home Page Display');
CREATE TABLE IF NOT EXISTS `invoice_columns` (
  `doc_type` varchar(20) NOT NULL,
  `col_key` varchar(30) NOT NULL,
  `company_id` varchar(50) NOT NULL DEFAULT '',
  `col_header` varchar(50) NOT NULL,
  `col_visible` tinyint(1) NOT NULL DEFAULT '1',
  `col_order` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`doc_type`, `col_key`, `company_id`)
);
INSERT IGNORE INTO `invoice_columns` (`doc_type`, `col_key`, `col_header`, `col_visible`, `col_order`) VALUES
('invoice',  'sno',          '#',        1, 1),
('invoice',  'product_name', 'ITEMS',    1, 2),
('invoice',  'qty',          'QTY',      1, 3),
('invoice',  'mrp',          'MRP',      1, 4),
('invoice',  'net_rate',     'NET RATE', 1, 5),
('invoice',  'price',        'PRICE',    0, 6),
('invoice',  'disc',         'DISC %',   0, 7),
('invoice',  'disc_amt',     'DISC AMT', 1, 8),
('invoice',  'sub_total',    'SUB TOTAL',1, 9),
('invoice',  'tax_pct',      'TAX %',    0, 10),
('invoice',  'tax_amt',      'TAX AMT',  1, 11),
('invoice',  'amount',       'AMOUNT',   0, 12),
('invoice',  'hsn',          'HSN',      1, 13),
('invoice',  'mfg_date',     'MFG DATE', 0, 14),
('invoice',  'exp_date',     'EXP DATE', 0, 15),
('invoice',  'total',        'TOTAL',    1, 16),
('estimate', 'sno',          '#',        1, 1),
('estimate', 'product_name', 'ITEMS',    1, 2),
('estimate', 'qty',          'QTY',      1, 3),
('estimate', 'mrp',          'MRP',      1, 4),
('estimate', 'net_rate',     'NET RATE', 1, 5),
('estimate', 'price',        'PRICE',    0, 6),
('estimate', 'disc',         'DISC %',   1, 7),
('estimate', 'disc_amt',     'DISC AMT', 1, 8),
('estimate', 'sub_total',    'SUB TOTAL',1, 9),
('estimate', 'tax_pct',      'TAX %',    0, 10),
('estimate', 'tax_amt',      'TAX AMT',  1, 11),
('estimate', 'amount',       'AMOUNT',   0, 12),
('estimate', 'hsn',          'HSN',      0, 13),
('estimate', 'mfg_date',     'MFG DATE', 0, 14),
('estimate', 'exp_date',     'EXP DATE', 0, 15),
('estimate', 'total',        'TOTAL',    1, 16),
-- purchase entry columns
('purchase', 'mrp',          'MRP',          1,  1),
('purchase', 'rprice',       'Retail Price', 1,  2),
('purchase', 'wprice',       'Wholesale Pr', 0,  3),
('purchase', 'disc',         'Disc %',       1,  4),
('purchase', 'disc_amt',     'Disc Amt',     1,  5),
('purchase', 'sub_total',    'Sub Total',    1,  6),
('purchase', 'tax_pct',      'Tax %',        1,  7),
('purchase', 'tax_amt',      'Tax Amt',      1,  8),
('purchase', 'hsn',          'HSN',          1,  9),
('purchase', 'tax_type',     'Tax Type',     1, 10),
('purchase', 'category',     'Category',     1, 11),
('purchase', 'manufacturer', 'Manufacturer', 1, 12),
('purchase', 'size',         'SIZE',         0, 13),
('purchase', 'color',        'COLOR',        0, 14),
('purchase', 'brand',        'BRAND',        0, 15),
-- purchase order columns
('po',       'mrp',          'MRP',            1, 1),
('po',       'reorder_level','Re-Order Level', 1, 2),
('po',       'stock_hand',   'Stock-in-Hand',  1, 3),
('po',       'tax_pct',      'Tax %',          1, 4),
('po',       'tax_amt',      'Tax Amt',        1, 5),
('po',       'total',        'Total',          1, 6),
('po',       'size',         'SIZE',           0, 7),
('po',       'color',        'COLOR',          0, 8),
('po',       'brand',        'BRAND',          0, 9);

-- Other charges master table
CREATE TABLE IF NOT EXISTS `other_charges_master` (
    `id`          INT AUTO_INCREMENT PRIMARY KEY,
    `charge_name` VARCHAR(100) NOT NULL,
    `company_id`  VARCHAR(20) NOT NULL DEFAULT '',
    UNIQUE KEY `uk_name_company` (`charge_name`, `company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Other charges detail table for sales
CREATE TABLE IF NOT EXISTS `sales_other_charges` (
    `id`          INT AUTO_INCREMENT PRIMARY KEY,
    `billno`      INT NOT NULL,
    `charge_name` VARCHAR(100) NOT NULL,
    `amount`      DOUBLE NOT NULL DEFAULT 0,
    `company_id`  VARCHAR(20) NOT NULL DEFAULT '',
    KEY `idx_soc_billno_company` (`billno`, `company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Other charges detail table for estimate
CREATE TABLE IF NOT EXISTS `estimate_other_charges` (
    `id`          INT AUTO_INCREMENT PRIMARY KEY,
    `billno`      INT NOT NULL,
    `charge_name` VARCHAR(100) NOT NULL,
    `amount`      DOUBLE NOT NULL DEFAULT 0,
    `company_id`  VARCHAR(20) NOT NULL DEFAULT '',
    KEY `idx_eoc_billno_company` (`billno`, `company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Seed default charge names for every existing company
INSERT IGNORE INTO `other_charges_master` (`charge_name`, `company_id`)
SELECT t.charge_name, c.companyID
FROM (SELECT 'Packing Charges' AS charge_name
      UNION ALL SELECT 'Freight'
      UNION ALL SELECT 'Loading Charges'
      UNION ALL SELECT 'Installation'
      UNION ALL SELECT 'Insurance'
      UNION ALL SELECT 'Labour Charges'
      UNION ALL SELECT 'Transport'
      UNION ALL SELECT 'Other') t
CROSS JOIN company c;