ALTER TABLE estimate_items ADD COLUMN IF NOT EXISTS size VARCHAR(50) DEFAULT NULL;
ALTER TABLE estimate_items ADD COLUMN IF NOT EXISTS color VARCHAR(50) DEFAULT NULL;
ALTER TABLE estimate_items ADD COLUMN IF NOT EXISTS brand VARCHAR(100) DEFAULT NULL;
